"use strict";
// import express from "express";
Object.defineProperty(exports, "__esModule", { value: true });
// import express = require("express");
// import dotenv from "dotenv";
// import connectDB from "./config/db";
// import authRoutes from "./routes/authRoutes";
// import postRoutes from "./routes/postRoutes";
// import commentRoutes from "./routes/commentRoutes";
// import errorHandler from "./middlewares/errorHandler";
// dotenv.config();
// connectDB();
// const app  = express();
// app.use(express.json());
// app.use('/api/auth', authRoutes);
// app.use('/api/posts', postRoutes);
// app.use('/api/comments', commentRoutes);
// app.use(errorHandler);
// const PORT = process.env.PORT || 5000;
// app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
